### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')

### ISSUE THREAD

**Issue by bbednarek** [gradle-update/update-gradle-wrapper-action#382]
I am getting following error when I ran update gradle wrapper action 
```
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Download action repository 'gradle-update/update-gradle-wrapper-action@v1'
Download action repository 'gradle/wrapper-validation-action@v1'
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load gradle-update/update-gradle-wrapper-action/v1/action.yml
```

I believe [this change](https://github.com/gradle-update/update-gradle-wrapper-action/commit/776a4af094b6b396281a9a8eb33883794f47740c#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6) caused it.

**Comment by cristiangreco** [comment]
Hey @bbednarek thanks for reporting this issue. I can't reproduce it, do you have an example repo and/or a workflow file that triggers the error?

**Comment by bbednarek** [comment]
Hey @cristiangreco thanks for the reply.
I'd like to mention that we use self-hosted github runners. 

Workflow file looks like this
```
name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 9 * * MON"

jobs:
  update-gradle-wrapper:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES_GH_PACKAGES_READ_TOKEN: ${{ secrets.GRADLE_PROPERTIES_GH_PACKAGES_READ_TOKEN }}
          GRADLE_PROPERTIES_GH_PACKAGES_WRITE_TOKEN: ${{ secrets.GRADLE_PROPERTIES_GH_PACKAGES_WRITE_TOKEN }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=$HOME/.gradle" >> $GITHUB_ENV
          echo "githubUser=finmid-sre" > ~/.gradle/gradle.properties
          echo "githubPackagesReadToken=${GRADLE_PROPERTIES_GH_PACKAGES_READ_TOKEN}" >> ~/.gradle/gradle.properties
          echo "githubToken=${GRADLE_PROPERTIES_GH_PACKAGES_WRITE_TOKEN}" >> ~/.gradle/gradle.properties
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: dependencies
          repo-token: ${{ secrets.GH_WORKFLOW_TOKEN }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
```

**Comment by cristiangreco** [comment]
> I'd like to mention that we use self-hosted github runners.

Could you please check that node v16 is available in your runner environment? GitHub actions support `node16` since December, see the following announcement and docs:
- https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/
- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by cristiangreco** [comment]
Thank you for double-checking!
